FROM python:3.11-slim

WORKDIR /app

RUN pip install --no-cache-dir \
    google-cloud-monitoring \
    google-cloud-run \
    python-dotenv

COPY src/scaler.py ./src/scaler.py

CMD ["python", "-m", "src.scaler"]
